name:                todo
version:             0.1.0.0
github:              "jbweston/todo"
license:             BSD3
author:              "Joseph Weston"
maintainer:          "joseph@weston.cloud"
copyright:           "Copyright (c) 2020 Joseph Weston"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jbweston/todo#readme>

dependencies:
- base >= 4.7 && < 5
- text
- time

library:
  source-dirs: src

executables:
  todo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - todo

tests:
  todo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - todo
    - hspec
    build-tools:
    - hspec-discover
